version: '3.8'
services:
  sermo-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serm
    networks:
      - sermosymmetry
networks:
  sermosymmetry:
